"""Derive Clocky AM PM Marker from bundled Poppins 400 (SIL OFL 1.1).

Run from any directory with fontTools 4.53.1. Output is committed; no runtime dependency.
Required ligatures, rather than discretionary ligatures, keep the hour substitution active
with nonzero letter spacing. This face belongs only to the AM/PM TextClock.
"""
from pathlib import Path
import unicodedata

from fontTools.ttLib import TTFont
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.feaLib.builder import addOpenTypeFeaturesFromString
from fontTools import subset
from generate_face_layouts import SHADOWS, attrs

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "app/src/main/res/font/clocky_poppins_400.ttf"
OUTPUT = ROOT / "app/src/main/res/font/clocky_ampm_marker.ttf"


def generate():
    font = TTFont(SOURCE, recalcTimestamp=False)
    cmap = font.getBestCmap()
    digits = [cmap[ord(str(i))] for i in range(10)]
    # Retain source outlines and metrics, composing A/P + M as one substitution glyph.
    for label in ("AM", "PM"):
        first, second = [cmap[ord(c)] for c in label]
        pen = TTGlyphPen(font.getGlyphSet())
        advance = font["hmtx"].metrics[first][0]
        pen.addComponent(first, (1, 0, 0, 1, 0, 0))
        pen.addComponent(second, (1, 0, 0, 1, advance, 0))
        name = "clocky" + label
        order = list(font.getGlyphOrder())
        font["glyf"][name] = pen.glyph()
        font["hmtx"].metrics[name] = (advance + font["hmtx"].metrics[second][0], font["hmtx"].metrics[first][1])
        font.setGlyphOrder(order + [name])
    for tag in ("GSUB", "GPOS", "GDEF"):
        if tag in font:
            del font[tag]
    rules = [f"sub {digits[h // 10]} {digits[h % 10]} by clocky{'AM' if h < 12 else 'PM'};" for h in range(24)]
    addOpenTypeFeaturesFromString(font, "languagesystem DFLT dflt;\nlanguagesystem latn dflt;\nfeature rlig {\n" + "\n".join(rules) + "\n} rlig;")
    # Locale-shaped decimal digits must select the same hour glyphs, including Arabic.
    for table in font["cmap"].tables:
        if table.isUnicode() and table.format in (4, 12):
            for cp in range(0x10000 if table.format == 4 else 0x110000):
                if unicodedata.category(chr(cp)) == "Nd":
                    table.cmap[cp] = digits[unicodedata.decimal(chr(cp))]
    names = {1: "Clocky AM PM Marker", 2: "Regular", 3: "Clocky-AM-PM-Marker-1", 4: "Clocky AM PM Marker Regular", 6: "ClockyAMPMMarker-Regular", 16: "Clocky AM PM Marker", 17: "Regular"}
    font["name"].names = [n for n in font["name"].names if n.nameID not in names]
    for name_id, value in names.items():
        font["name"].setName(value, name_id, 3, 1, 0x409)
    options = subset.Options()
    options.layout_features = ["rlig"]
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
    options.name_legacy = True
    sub = subset.Subsetter(options=options)
    sub.populate(glyphs=digits + [cmap[ord(c)] for c in "AMP"] + ["clockyAM", "clockyPM"])
    sub.subset(font)
    font.save(OUTPUT)
    for suffix, _, shadow in SHADOWS:
        xml = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/fonts/generate_ampm_marker.py. Marker only; never a selectable font. -->\n'
        xml += '<TextClock xmlns:android="http://schemas.android.com/apk/res/android"\n'
        xml += '    android:id="@+id/clocky_ampm_marker"\n    android:layout_width="wrap_content"\n    android:layout_height="wrap_content"\n'
        xml += '    android:fontFamily="@font/clocky_ampm_marker"\n    android:importantForAccessibility="no"\n'
        xml += '    android:includeFontPadding="false"\n    android:singleLine="true"\n'
        xml += attrs(shadow, 4)
        xml += '    android:textColor="@android:color/white" />\n'
        (ROOT / f"app/src/main/res/layout/clocky_face_ampm_marker{suffix}.xml").write_text(xml, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.name}: {OUTPUT.stat().st_size} bytes")


if __name__ == "__main__":
    generate()
