#!/usr/bin/env python
"""Generates Clocky's font-fragment layouts and the Kotlin table that maps them.

A font fragment is one TextClock face (or one per available weight) that DigitalWidgetComposer adds
into a template slot. RemoteViews cannot call setShadowLayer or pick a bundled font at runtime, so
every (family, date-caps, legibility-shadow) combination is a pre-built layout
(docs/architecture/PHASE_2_STUDIO.md section 5).

Run from the repository root:  python tools/fonts/generate_face_layouts.py

It never touches the six hand-written Phase 1A CLASSIC layouts (shadow of the AOSP widget); it
emits every other combination, the sans-serif shadow styles, and FontFragmentTable.kt. The output
is committed; rerun after changing FAMILIES.
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
RES = os.path.join(ROOT, "app", "src", "main", "res")
KOTLIN = os.path.join(
    ROOT, "app", "src", "main", "java", "com", "stupidsavacan", "clocky", "widget", "digital", "FontFragmentTable.kt"
)

# (layout slug, font id, kind, extra)
#   kind "sans":     system sans, nine weight faces driven by styles Clocky.Face.SystemSans.W###
#   kind "platform": single TextClock with a platform android:fontFamily alias
#   kind "bundled":  one TextClock per available weight, each with its own @font/<file>
FAMILIES = [
    ("system_sans", "system-sans", "sans", None),
    ("sans_serif_light", "sans-serif-light", "platform", "sans-serif-light"),
    ("sans_serif_rounded", "sans-serif-rounded", "platform", "sans-serif-rounded"),
    ("serif", "serif", "platform", "serif"),
    ("sans_serif_condensed", "sans-serif-condensed", "platform", "sans-serif-condensed"),
    ("monospace", "monospace", "platform", "monospace"),
    ("poppins", "clocky-poppins", "bundled", ("clocky_poppins", [300, 400, 500, 600, 700])),
    ("varela_round", "clocky-varela-round", "bundled", ("clocky_varela_round", [400])),
    ("dm_serif_display", "clocky-dm-serif-display", "bundled", ("clocky_dm_serif_display", [400])),
    ("barlow_condensed", "clocky-barlow-condensed", "bundled", ("clocky_barlow_condensed", [300, 400, 500, 600, 700])),
    ("plex_mono", "clocky-plex-mono", "bundled", ("clocky_plex_mono", [300, 400, 500, 700])),
    ("bebas_neue", "clocky-bebas-neue", "bundled", ("clocky_bebas_neue", [400])),
]
HAND_WRITTEN = {"system_sans", "sans_serif_light", "sans_serif_rounded", "serif", "sans_serif_condensed", "monospace"}

# (suffix, Kotlin ShadowVariant, shadow attrs or None for "no shadow")
CLASSIC_ATTRS = [
    ("shadowColor", "@color/widget_shadow_color"),
    ("shadowDy", "@dimen/widget_shadow_dy"),
    ("shadowRadius", "@dimen/widget_shadow_radius"),
]
SHADOWS = [
    ("", "CLASSIC", CLASSIC_ATTRS),
    ("_off", "OFF", []),
    ("_soft_dark", "SOFT_DARK", [("shadowColor", "#66000000"), ("shadowDy", "1.5"), ("shadowRadius", "3")]),
    ("_soft_light", "SOFT_LIGHT", [("shadowColor", "#66FFFFFF"), ("shadowDy", "1.5"), ("shadowRadius", "3")]),
    ("_strong_dark", "STRONG_DARK", [("shadowColor", "#E6000000"), ("shadowDy", "2"), ("shadowRadius", "6")]),
    ("_strong_light", "STRONG_LIGHT", [("shadowColor", "#E6FFFFFF"), ("shadowDy", "2"), ("shadowRadius", "6")]),
]
HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Clocky font fragment (CLOCKY_END_STATE.md section 12): added into a template slot with RemoteViews.addView.\n"
    "     Generated by tools/fonts/generate_face_layouts.py; do not edit by hand. -->\n"
)
NS = 'xmlns:android="http://schemas.android.com/apk/res/android"'


def attrs(lines, indent):
    pad = " " * indent
    return "".join(f'{pad}android:{k}="{v}"\n' for k, v in lines)


def text_clock(view_id, indent, family_attr, shadow, caps, style=None, visible=True):
    pad = " " * indent
    body = f'{pad}<TextClock\n'
    if style:
        body += f'{pad}    style="@style/{style}"\n'
    body += f'{pad}    android:id="@+id/{view_id}"\n'
    body += f'{pad}    android:layout_width="wrap_content"\n'
    body += f'{pad}    android:layout_height="wrap_content"\n'
    body += f'{pad}    android:ellipsize="none"\n'
    if family_attr:
        body += f'{pad}    android:fontFamily="{family_attr}"\n'
    body += f'{pad}    android:includeFontPadding="false"\n'
    body += f'{pad}    android:singleLine="true"\n'
    body += attrs(shadow, indent + 4)
    if caps:
        body += f'{pad}    android:textAllCaps="true"\n'
    body += f'{pad}    android:textColor="@android:color/white"'
    body += ('\n' + f'{pad}    android:visibility="gone"' if not visible else "")
    body += " />\n"
    return body


def layout_xml(kind, extra, caps, shadow_suffix, shadow):
    if kind == "platform":
        # Single face; the root is the face itself (it is also the id the composer targets).
        x = HEADER + f"<TextClock\n    {NS}\n"
        x += '    android:id="@+id/clocky_face_single"\n    android:layout_width="wrap_content"\n'
        x += '    android:layout_height="wrap_content"\n    android:ellipsize="none"\n'
        x += f'    android:fontFamily="{extra}"\n    android:includeFontPadding="false"\n    android:singleLine="true"\n'
        x += attrs(shadow, 4)
        if caps:
            x += '    android:textAllCaps="true"\n'
        return x + '    android:textColor="@android:color/white" />\n'
    x = HEADER + f'<FrameLayout\n    {NS}\n    android:layout_width="wrap_content"\n    android:layout_height="wrap_content">\n\n'
    if kind == "sans":
        views = []
        for w in range(100, 1000, 100):
            style = f"Clocky.Face.SystemSans.W{w}" + (shadow_suffix_style(shadow_suffix) if shadow_suffix else "")
            views.append(text_clock(f"clocky_face_w{w}", 4, None, [], caps, style=style, visible=False))
    else:
        file_base, weights = extra
        views = [
            text_clock(f"clocky_face_w{w}", 4, f"@font/{file_base}_{w}", shadow, caps, visible=False)
            for w in weights
        ]
    return x + "\n".join(views) + "</FrameLayout>\n"


def shadow_suffix_style(suffix):
    return "".join(p.capitalize() for p in suffix.strip("_").split("_")).join([".", ""])


def styles_xml():
    out = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/fonts/generate_face_layouts.py; do not edit by hand. -->\n<resources>\n'
    for suffix, _, attrs_ in SHADOWS:
        if not suffix:
            continue
        name = shadow_suffix_style(suffix)[1:]
        for w in range(100, 1000, 100):
            out += f'    <style name="Clocky.Face.SystemSans.W{w}.{name}" parent="Clocky.Face.SystemSans.W{w}">\n'
            if not attrs_:
                out += '        <item name="android:shadowColor">@android:color/transparent</item>\n'
                out += '        <item name="android:shadowRadius">0</item>\n        <item name="android:shadowDy">0</item>\n'
            else:
                for k, v in attrs_:
                    out += f'        <item name="android:{k}">{v}</item>\n'
            out += "    </style>\n"
    return out + "</resources>\n"


def main():
    table = []
    for slug, font_id, kind, extra in FAMILIES:
        for caps in (False, True):
            for suffix, variant, shadow in SHADOWS:
                name = f"clocky_face_{slug}{'_caps' if caps else ''}{suffix}"
                table.append((font_id, caps, variant, name))
                if slug in HAND_WRITTEN and not suffix:
                    continue
                path = os.path.join(RES, "layout", name + ".xml")
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(layout_xml(kind, extra, caps, suffix, shadow))
    with open(os.path.join(RES, "values", "clocky_face_shadow_styles.xml"), "w", encoding="utf-8", newline="\n") as f:
        f.write(styles_xml())
    lines = [
        "package com.stupidsavacan.clocky.widget.digital",
        "",
        "import androidx.annotation.LayoutRes",
        "import com.android.deskclock.R",
        "import com.stupidsavacan.clocky.design.resolve.ShadowVariant",
        "",
        "/** Generated by tools/fonts/generate_face_layouts.py; do not edit by hand. */",
        "internal object FontFragmentTable {",
        "    private data class Key(val fontId: String, val caps: Boolean, val shadow: ShadowVariant)",
        "",
        "    private val layouts: Map<Key, Int> = mapOf(",
    ]
    for font_id, caps, variant, name in table:
        lines.append(f'        Key("{font_id}", {str(caps).lower()}, ShadowVariant.{variant}) to R.layout.{name},')
    lines += [
        "    )",
        "",
        "    @LayoutRes",
        "    fun layoutFor(fontId: String, caps: Boolean, shadow: ShadowVariant): Int? = layouts[Key(fontId, caps, shadow)]",
        "}",
        "",
    ]
    with open(KOTLIN, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{len(table)} layouts mapped")


if __name__ == "__main__":
    main()
